### ISSUE TITLE
VSCode git implementation

### ISSUE THREAD

**Issue by jhechtf** [benjaminadk/emojigit#10]
I was going through your readme and noticed that you have plans to interact with vscode's git api. I have some experience working with it (I created a quick addon and didn't want to reinvent the wheel). 

If you feel like you need some help, go ahead and ping me here. 

If you already know what you're doing then no worries, but I figured I'd offer just in case you needed it.

**Comment by benjaminadk** [comment]
I was looking into using the vscode git api to take advantage of the commit text input box, especially with the `autoCommit` feature. I played around with it but the git api didnt seem to expose all the functionality I was looking for. Right now I do use the git api only to check if there are active repositories. Now that I think about it, it would probably be better to take that code out so using the extension doesn't require having the git extension enabled (although I assume most people do keep it on). Thanks for the offer, and if I not mistaken if you had the idea about custom emoji maps? Did you use it yet? As far as git api, I just dont think it exposes what I wanted.

**Comment by jhechtf** [comment]
I haven't had a chance to use it yet -- I plan to soon.

What functionality are you trying to do? I can confirm that you can set text in the main git checkbox, and what if you were to utilize the vscode git if it was enabled, and default to using the terminal otherwise?

**Comment by jhechtf** [comment]
self-closing the issue, since it's not really an issue.
