### ISSUE TITLE
Bug: Merging branches emoji incorrect

### ISSUE THREAD

**Issue by smeagolem** [benjaminadk/emojigit#9]
`:twisted_rightwards_arrows:` - :twisted_rightwards_arrows:
Is missing an ending **"s"** in the config. As seen below.
`{ emoji: '🔀', colon: ':twisted_rightwards_arrow:', text: 'Merging branches' },`

**Comment by benjaminadk** [comment]
Good eye.

https://github.com/benjaminadk/emojigit/commit/8676eabf7c4c02e9c181c75393484561aa332669
